### ISSUE TITLE
DEPRECATED: Function get_magic_quotes_runtime()

### ISSUE THREAD

**Issue by frase-git** [cmb69/polyglot_xh#22]
XH 1.7.5
PHP 1.7.4
Polyglott_XH 1.0beta2

Debug mode wrote:

> DEPRECATED: Function get_magic_quotes_runtime() is deprecated
> ... \plugins\polyglott\classes\Controller.php:259

**Comment by cmb69** [comment]
Yes, already fixed in the meantime, see #20.

**Comment by frase-git** [comment]
> Yes, already fixed in the meantime, see #20.

Oh, sorry. Once again, I didn't look properly.
By the way, under PHP 8.1 (without the patch) there is a white page with the error message.

**Comment by cmb69** [comment]
> Oh, sorry. Once again, I didn't look properly.

No problem. Better report twice, than not to report at all. :)

> By the way, under PHP 8.1 (without the patch) there is a white page with the error message.

Which error message?

**Comment by frase-git** [comment]
> Which error message?

PHP 8.1.1

> Uncaught Error: Call to undefined function get_magic_quotes_runtime() in ... \plugins\polyglott\classes\Controller.php:259
> Stack trace:
> #0 ... \plugins\polyglott\classes\Controller.php(294): Polyglott_Controller->systemChecks()
> #1 ... \plugins\polyglott\classes\Controller.php(146): Polyglott_Controller->info()
> #2 ... \plugins\polyglott\classes\Controller.php(76): Polyglott_Controller->handleAdministration()
> #3 ... \plugins\polyglott\index.php(68): Polyglott_Controller->dispatch()
> #4 ... \cmsimple\cms.php(1112): include('...')
> #5 ... \index.php(6): include('...')
> #6 {main}
> thrown in ... \plugins\polyglott\classes\Controller.php on line 259

**Comment by frase-git** [comment]
> Need to do something about that soon.

I think so too.
The message here is:

master under PHP 8.1.1 (xampp win)

Uncaught Error: Class "Plib\Url" not found in ... \plugins\polyglot\classes\Plugin.php:119
Stack trace:
#0 ... \plugins\polyglot\classes\Plugin.php(133): Polyglot\Plugin::url()
#1 ... \plugins\polyglot\classes\Plugin.php(47): Polyglot\Plugin::getModel()
#2 ... \plugins\polyglot\index.php(22): Polyglot\Plugin::run()
#3 ... \cmsimple\cms.php(1112): include('D:\\xampp_811\\ht...')
#4 ... \index.php(6): include('D:\\xampp_811\\ht...')
#5 {main}
thrown in ... \plugins\polyglot\classes\Plugin.php on line 119

**Comment by frase-git** [comment]
Plib_XH - I have now copied in - and behold, the described message is gone ;-)

**Comment by cmb69** [comment]
> Only, Plib_XH - does not appear in the plugin list at all.

Yeah, it's in early development.
